### ISSUE TITLE
Definir stack tecnológico

### ISSUE THREAD

**Issue by idaroga** [HandyFacts/recomendacion_mercado_inmobiliario#14]
Para cada equipo de datos (data engineering, data scientist y data analysis) realizar las siguientes tareas

- Propuesta de tecnologías a usar y breve explicación de por qué se eligieron.
- Crear una wiki llamada "Stack tecnológico Data ______" con la descripción de cada una de las propuestas elegidas

Material de apoyo: [Qué es un stack tecnológico?](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-Tecnol%C3%B3gico)

**Comment by idaroga** [comment]
Creación de un wiki con el issue 14 indicando qué es un stack tecnológico

**Comment by LucasAugusto-py** [comment]
✈Se agregó definición y justificación del stack tecnológico para el Back-end en la [Wiki](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki): - [Stack Tecnologico Data Engineer](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-tecnol%C3%B3gico-Data-Engineering).
#### Por definir y justificar:
* Front-end
* Servicio Cloud

**Comment by LucasAugusto-py** [comment]
Se agregó descripción del Front-end✅, aunque es necesario resaltar de que es el apartado del stack tecnológico más suceptible a **cambios**

**Comment by Yuliedpardo** [comment]
✈Se agregó definición y justificación del stack tecnológico para Google Cloud Storage en la [Wiki](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki): - [Stack Tecnologico Data Engineer](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-tecnol%C3%B3gico-Data-Engineering).

Por definir y justificar:

Servicio Cloud

**Comment by Yuliedpardo** [comment]
✈Se agregó definición y justificación del stack tecnológico para Google Cloud Funtions en la [Wiki](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki): - [Stack Tecnologico Data Engineer](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-tecnol%C3%B3gico-Data-Engineering).

**Comment by Yuliedpardo** [comment]
✈Se agregó definición y descripción de Google Cloud Scheduler en la [Wiki](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki): - [Stack Tecnologico Data Engineer](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-tecnol%C3%B3gico-Data-Engineering).

**Comment by Aalg26** [comment]
se subio el stack [tecnologico preliminar](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Stack-Tecnol%C3%B3gico--Data-Analyst#data-scientist) de Data science
