### ISSUE TITLE
Ajustar Modelo 2: Modelo de recomendación de propiedades

### ISSUE THREAD

**Issue by idaroga** [HandyFacts/recomendacion_mercado_inmobiliario#152]
- [x] Ajustar precisión del modelo 

- [x] Definir las columnas que va a sacar el modelo 

- [ ] Iván actualiza el README con el link del archivo con el proceso del ETL

**Comment by idaroga** [comment]
//Revisar la descripción del modelo 2 que se encuentra en ([click aca](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/1-product-backlog#52-modelo-2-sistema-de-recomendaci%C3%B3n-de-propiedades)) y de ser preciso adjuntar en un comentario de esta issue la descripción correcta

**Comment by idaroga** [comment]
- [ x ] @idaroga explica la implementación del código de los modelos en Google Functions (descartado)

**Comment by Aalg26** [comment]
el modelo analiza las características mas influyentes en el precio de los inmuebles y las utiliza para estimar el precio de venta posible para dicha propiedad

**Comment by Aalg26** [comment]
modelo ajustado por lo que se cierra la issue

**Comment by idaroga** [comment]
Queda pendiente la carga del dataset unificado al DW

Encargados:
- @Aalg26 
- @LucasAugusto-py

**Comment by Aalg26** [comment]
dataset actualizado

**Comment by idaroga** [comment]
descripción actualizada
nombre del modelo actualizado
link actualizado
