### ISSUE TITLE
EDA Preliminar

### ISSUE THREAD

**Issue by idaroga** [HandyFacts/recomendacion_mercado_inmobiliario#23]
Todo el equipo consultará los datasets que se encuentran disponibles para validar con que datos se cuentan. El objetivo es encontrar datasets relacionados con cada uno de los objetivos del proyecto

[Propuesta Henry](https://github.com/soyHenry/PF_DS/blob/main/Proyectos/airbnb_house_market.md)

[Datasets Google Drive](https://drive.google.com/drive/folders/1rHg223rnD1xxi6IQJ98aLQGjsiJiDK5r)

## Realizar el proceso de EDA:

- [ ] Revisar tipo de datos vs. tipo de variable
- [ ] Estadística descriptiva de los datos
- [ ] Visualización gráfica de los datos
- [ ] Manejo de valores nulos
- [ ] Detección de atípicos
- [ ] Análisis de relaciones

Material de apoyo: [Analisis Exploratorio de Datos](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/wiki/Proceso-de-EDA)

## Objetivos asignados para encontrar datasets (Data engineering):
- [ ] Disminución en los precios de la vivienda
- [ ] Aumento en la tasa de morosidad y ejecuciones hipotecarias
- [ ] Caída en la construcción de viviendas

## Objetivos asignados para encontrar datasets  (Data science):
- [ ] Menor actividad en el sector inmobiliario (actividad: compra, ventas y alquileres)
- [ ] Mayor disponibilidad de propiedades en el mercado (mayor oferta que demanda de propiedades para compra, venta o alquiler)
- [ ] Aumento de tasas de interés
- [ ] Indicadores económicos (cuales y cómo se comportan)

**Comment by bere44** [comment]
**De acuerdo al objetivo**:

- Determinar el aumento de la tasa de interes hipotecario y los indicadores economicos relevantes

- En el [dataset](https://colab.research.google.com/drive/1YFPaMP9aH2vYHxJR3vIdHx9fx6MwUUOU#scrollTo=8_KIfhhb4SY0) que adjunto se puede ver las tasas de interes hipotecario a nivel semanal, tambien se puede ver los indicicadores economicos tales como la tasa de desempleo, la inflacion y el PBI.

- Faltaria definir que temporalidad deben tener los datos.

**Comment by bere44** [comment]
Tambien se tiene que replantear  los objetivos especificos.

**Objetivo 1:** Determinar si existe:

-	Disminución en los precios de la vivienda: Es un indicador importante ya que una disminución en los precios puede indicar una posible recesión en el sector inmobiliario.
-	Aumento en la tasa de morosidad y ejecuciones hipotecarias: La morosidad y las ejecuciones hipotecarias generalmente aumentan durante una recesión.
-	Caída en la construcción de viviendas: Una disminución en la construcción de viviendas puede ser un indicio de una recesión en el sector inmobiliario, ya que refleja una menor demanda y actividad.
-	Menor actividad en el sector inmobiliario (actividad: compra, ventas y alquileres): Este indicador es fundamental, ya que una menor actividad en términos de compra, ventas y alquileres sugiere una posible recesión en el sector.
-	Mayor disponibilidad de propiedades en el mercado: Un exceso de oferta en comparación con la demanda puede ser un signo de una recesión en el sector inmobiliario.
-	Aumento de tasas de interés de créditos hipotecarios: Las tasas de interés más altas pueden desalentar a los compradores y afectar la demanda de viviendas, por lo que es pertinente considerar este indicador.

**Objetivo2:** Relacionar los Indicadores económicos (PIB, desempleo e inflación): El PIB, el desempleo y la inflación son factores macroeconómicos que pueden tener un impacto significativo en el sector inmobiliario, y analizar su influencia puede proporcionar un panorama más completo.

**Comment by bere44** [comment]
De acuerdo a todos los cambios que ha habido, se tuvo que modificar los datos y por ende varios archivos como el EDA de la demanda. Adjunto el archivo de [colab](https://colab.research.google.com/drive/1CkoCRKsOdaiRDykT7sC_1bYRCPiwG2xm?usp=drive_link).
