### ISSUE TITLE
Planteamiento de KPIs

### ISSUE THREAD

**Issue by idaroga** [HandyFacts/recomendacion_mercado_inmobiliario#26]
Definir 5 objetivos específicos del proyecto y relacionar cada uno con un KPI. Esto será documentado dentro del PRODUCT BACKLOG ubicado en la sección del readme del proyecto.

[README del proyecto](https://github.com/orgs/HandyFacts/projects/2?pane=info)

**Comment by Yuliedpardo** [comment]
kpi 1 : Tasa de Vacancia de Viviendas (Vacancy Rate): La tasa de vacancia de viviendas mide la proporción de viviendas desocupadas en comparación con el total de viviendas disponibles en una determinada área o región. Un aumento en la tasa de vacancia podría indicar una menor demanda de viviendas y posiblemente una recesión en el mercado inmobiliario.

kpi 2: Índice de Accesibilidad a Préstamos Hipotecarios (Mortgage Affordability Index): Este índice evalúa la accesibilidad de la población a los préstamos hipotecarios, considerando factores como los ingresos medios, las tasas de interés y los precios de las viviendas. Una disminución en este índice puede indicar dificultades económicas y posiblemente una recesión.

kpi 3: Tasa de Participación de Inversores en el Mercado Inmobiliario (Real Estate Investor Participation Rate): Este KPI evalúa la participación de inversores en el mercado inmobiliario, indicando cuántos compradores de viviendas son inversores en lugar de compradores de vivienda primarios. Un aumento en esta tasa puede indicar especulación excesiva y afectar la estabilidad del mercado.

kpi 4: Tasa de Incumplimiento de Pagos de Hipotecas (Mortgage Delinquency Rate): Este KPI mide la proporción de propietarios de viviendas que están en mora en sus pagos hipotecarios. Un aumento en esta tasa puede señalar dificultades financieras en los propietarios y posiblemente un mercado inmobiliario en declive.
Índice de Construcción de Nuevas Viviendas (New Housing Construction Index): Este KPI rastrea la cantidad de nuevas viviendas en construcción en comparación con un período base. Una disminución en este índice puede indicar una desaceleración en la industria de la construcción de viviendas y posiblemente una recesión inminente.

**Comment by bere44** [comment]
**KPI 5:** Aumento de indicadores económicos en un 1%: Se busca identificar un aumento del 1% en indicadores clave como el desempleo y la inflación durante el último año en comparación con el año anterior. Esto podría indicar un deterioro de la situación económica y potencialmente una señal de recesión.

**KPI 6:** Aumento de la tasa de interés hipotecaria en más del 3%: El objetivo es detectar un aumento de al menos el 3% en la tasa de interés de las hipotecas en los últimos 12 meses, en comparación con el año anterior. Un incremento significativo en las tasas de interés puede impactar negativamente en la demanda de viviendas y ser un indicador de posibles dificultades económicas.

**Comment by idaroga** [comment]
Quedo pendiente de sus comentarios para actualizarlos en la documentación del proyecto 😋

@bere44 @Aalg26

**Comment by Aalg26** [comment]
**1. Incremento del Rendimiento de Inversiones:**
   - **Objetivo:** Lograr un incremento del 10% en el rendimiento de las inversiones en comparación con el período de los 5 años anteriores a la contratación de los servicios de Handy Facts, considerando que el rendimiento previo no excedía el 5% de la inversión. El objetivo es superar significativamente el rendimiento histórico y generar un crecimiento sostenible en las inversiones.

   - **Fórmula de aumento porcentual:** 
     Aumento Porcentual = (Rendimiento Actual - Rendimiento Anterior) / Rendimiento Anterior * 100%

**2. Índice de Concentración de Cartera:**
   - **Objetivo:** Garantizar que el índice de concentración de la cartera se mantenga por debajo de 0.5 durante el período de contratación.

   - **Fórmula para Índice de Concentración Cartera:** 
     Índice de Concentración Cartera = Sumatoria de los Índices de Concentración por Estado / Número de Estados

   - **Fórmula para Índice de Concentración por Estado:** 
     Índice de Concentración por Estado = Valor de los Inmuebles en el Estado / Valor Total de la Cartera

**3. Eficacia Media en Predicciones:**
   - **Objetivo:** Garantizar una eficacia media en torno a 0.8. Este KPI evalúa la precisión del modelo al predecir el valor de venta de un inmueble en comparación con el valor real al que finalmente se vendió el inmueble.

   - **Fórmula para Eficacia por Transacción:**
     Eficacia por Transacción = (Valor Real de Venta - Valor Predicho por el Modelo) / Valor Real de Venta

   - **Fórmula para Eficacia Media:**
     Eficacia Media = Sumatoria de Eficacia / Número de Observaciones

**4. Índice de Retorno de Inversión (ROI) en Predicciones:**
   - **Objetivo:** Evaluar el valor generado por el modelo de predicción en comparación con los recursos invertidos en su desarrollo y mantenimiento.

   - **Fórmula ROI:** 
     ROI = (Beneficios Netos - Costos Totales) / Costos Totales * 100%

   - Mantener un ROI positivo indica rentabilidad.
