### ISSUE TITLE
Diseñar el modelo ER

### ISSUE THREAD

**Issue by idaroga** [HandyFacts/recomendacion_mercado_inmobiliario#37]
- El modelo debe incluir min 2 tablas de hechos y 5 dimensiones
- Documentar diagrama a través de una wiki

**Comment by idaroga** [comment]
Lucas si quieres carga el modelo ER acá y yo lo adjunto dentro de la wiki del diccionario de datos @LucasAugusto-py

**Comment by Aalg26** [comment]
[modelo ER](https://github.com/HandyFacts/recomendacion_mercado_inmobiliario/blob/main/src/logos/entidad-relacion.png)
